/**
 * AI-2038 (P4-C3) — Proposal store: status-queryable persistence + in-place revision.
 *
 * Follows src/store/observation-store.ts (better-sqlite3, WAL, private migrate(),
 * snake_case columns / camelCase TS). Proposals generated by proposal-generator.ts
 * persist here for human review.
 *
 * AC3.3 — proposals persist in a store queryable by status:
 *         pending / approved / rejected / applied / apply-failed / in-revision.
 * AC3.4 — revise: operator feedback attaches to the proposal; regeneration
 *         updates the proposal IN PLACE, preserving revision history
 *         (UX decision #3). The record always holds the CURRENT version; the
 *         superseded version's targets + the feedback that superseded it are
 *         pushed onto an immutable `revisions[]` thread.
 *
 * The `targets[]` core round-trips through SQLite as JSON. Lifecycle fields
 * (id/status/createdAt/updatedAt/revisions) live only on the stored record — the
 * deterministic core (proposal-generator.ts) carries none of them (AC3.2).
 */
import { computeIdempotencyKey as _computeIdempotencyKey, type GeneratedProposal, type ProposalTarget } from "./proposal-generator.js";
/** The six lifecycle statuses a stored proposal may hold (AC3.3). */
export declare const PROPOSAL_STATUSES: readonly ["pending", "approved", "rejected", "applied", "apply-failed", "in-revision"];
export type ProposalStatus = (typeof PROPOSAL_STATUSES)[number];
/** One entry in a proposal's immutable revision thread. */
export interface ProposalRevision {
    /** The superseded version this entry preserves. */
    version: number;
    /** The operator ask that superseded it. */
    feedback: string;
    /** The superseded version's regenerated targets. */
    targets: ProposalTarget[];
    idempotencyKey: string;
    createdAt: string;
}
/** A persisted proposal record — the deterministic core plus lifecycle fields. */
export interface ProposalRecord extends GeneratedProposal {
    id: number;
    status: ProposalStatus;
    createdAt: string;
    updatedAt: string;
    revisions: ProposalRevision[];
}
export declare class ProposalStore {
    private db;
    constructor(dbPath?: string);
    private migrate;
    /** Persist a freshly generated proposal at status `pending`. */
    create(p: GeneratedProposal): ProposalRecord;
    /** Fetch one proposal by id, or null if it does not exist. */
    get(id: number): ProposalRecord | null;
    /**
     * Query proposals, optionally filtered by status and/or workflow. Newest
     * first. `limit` is clamped to a sane maximum.
     */
    query(q?: {
        status?: ProposalStatus;
        workflowId?: string;
        limit?: number;
    }): ProposalRecord[];
    /** Transition a proposal to a new status. Rejects any value outside the enum. */
    setStatus(id: number, status: ProposalStatus): ProposalRecord;
    /**
     * Revise a proposal IN PLACE (AC3.4). The superseded version's targets and the
     * operator feedback that superseded it are appended to the immutable revision
     * thread; the record then advances to the regenerated targets, bumps its
     * version and moves to `in-revision`. The same row is mutated — no new row.
     */
    revise(id: number, feedback: string, regenerated: GeneratedProposal): ProposalRecord;
    close(): void;
}
/** Re-exported so callers have one import for the store and its key derivation. */
export declare const computeIdempotencyKey: typeof _computeIdempotencyKey;
//# sourceMappingURL=proposal-store.d.ts.map